### ISSUE TITLE
Does not work with Node.js 10 in dev mode

### ISSUE THREAD

**Issue by jakubklimek** [jaresan/simplod#1]
When I run `npm run start:dev`, the app does not work. It works in production mode.

**Comment by WhyINeedToFillUsername** [comment]
On windows, you have to use "set ... " for env. variables. In package.json:
`    "start:dev": "set NODE_ENV=development&& react-scripts start",`
(see https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json)
