### ISSUE TITLE
Wrong path accessed when loading/deleting a view

### ISSUE THREAD

**Issue by jakubklimek** [jaresan/simplod#3]
I have the following views (not all of them are actual views... `.meta` is not a view). When I created the view, I named it `test` and `view` in the directory `simplod`. However, in the app it says `simplodtest` and `simplodview` and then the app uses this string to access the file, which is not there:
![image](https://user-images.githubusercontent.com/718827/61460836-d914e500-a96f-11e9-9a4d-ccc0961866ef.png)
![image](https://user-images.githubusercontent.com/718827/61460849-de722f80-a96f-11e9-9ffc-16de97f78009.png)

**Comment by jaresan** [comment]
@jakubklimek Should be fixed now. Parsing `prefs.ttl` with base `folderUri` which wasn't ending with a slash caused problems. Now the slash is enforced when returning the `folderUri`, so the links should be composed properly. Regarding the `.meta`, everything of type `ldp:Resource` in the given folder is considered a view, will change that in the future.
